# Generated by Django 5.0.4 on 2024-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0002_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='template',
            field=models.ManyToManyField(blank=True, to='producte.producttemplate'),
        ),
    ]
