# Generated by Django 5.0.4 on 2024-04-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0003_alter_productcategory_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='parent_category',
            new_name='pare',
        ),
    ]
